.TH PESCO 1 "Last change: March 2012" Linux "User's Manuals"
.SH NAME
pesco \- Cognitive stimulation tool for elderly or cognitively impaired
.SH SYNOPSIS
.B pesco
.SH DESCRIPTION
.B Pesco
is a free software (EUPL) tool whose main goal is to provide cognitive stimulation for the elderly people and cognitive impaired. Its main goal is to evaluate and cognitively stimulate people to prevent the cognitive impairment, delaying the dependence from early stages. It provides test and exercises for the neurological and functional rehabilitation of memory, concentration, reasoning and organization.
.SH AUTHOR
GEDES Universidad de Granada <mjfortiz@ugr.es>
